/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { Shot } from "./Shot";
import { ShotCountArgs } from "./ShotCountArgs";
import { ShotFindManyArgs } from "./ShotFindManyArgs";
import { ShotFindUniqueArgs } from "./ShotFindUniqueArgs";
import { DeleteShotArgs } from "./DeleteShotArgs";
import { ShotService } from "../shot.service";
@graphql.Resolver(() => Shot)
export class ShotResolverBase {
  constructor(protected readonly service: ShotService) {}

  async _shotsMeta(
    @graphql.Args() args: ShotCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @graphql.Query(() => [Shot])
  async shots(@graphql.Args() args: ShotFindManyArgs): Promise<Shot[]> {
    return this.service.shots(args);
  }

  @graphql.Query(() => Shot, { nullable: true })
  async shot(@graphql.Args() args: ShotFindUniqueArgs): Promise<Shot | null> {
    const result = await this.service.shot(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => Shot)
  async deleteShot(@graphql.Args() args: DeleteShotArgs): Promise<Shot | null> {
    try {
      return await this.service.deleteShot(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
