/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { Cannon } from "./Cannon";
import { CannonCountArgs } from "./CannonCountArgs";
import { CannonFindManyArgs } from "./CannonFindManyArgs";
import { CannonFindUniqueArgs } from "./CannonFindUniqueArgs";
import { DeleteCannonArgs } from "./DeleteCannonArgs";
import { CannonService } from "../cannon.service";
@graphql.Resolver(() => Cannon)
export class CannonResolverBase {
  constructor(protected readonly service: CannonService) {}

  async _cannonsMeta(
    @graphql.Args() args: CannonCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @graphql.Query(() => [Cannon])
  async cannons(@graphql.Args() args: CannonFindManyArgs): Promise<Cannon[]> {
    return this.service.cannons(args);
  }

  @graphql.Query(() => Cannon, { nullable: true })
  async cannon(
    @graphql.Args() args: CannonFindUniqueArgs
  ): Promise<Cannon | null> {
    const result = await this.service.cannon(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => Cannon)
  async deleteCannon(
    @graphql.Args() args: DeleteCannonArgs
  ): Promise<Cannon | null> {
    try {
      return await this.service.deleteCannon(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
