/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { Angle } from "./Angle";
import { AngleCountArgs } from "./AngleCountArgs";
import { AngleFindManyArgs } from "./AngleFindManyArgs";
import { AngleFindUniqueArgs } from "./AngleFindUniqueArgs";
import { DeleteAngleArgs } from "./DeleteAngleArgs";
import { AngleService } from "../angle.service";
@graphql.Resolver(() => Angle)
export class AngleResolverBase {
  constructor(protected readonly service: AngleService) {}

  async _anglesMeta(
    @graphql.Args() args: AngleCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @graphql.Query(() => [Angle])
  async angles(@graphql.Args() args: AngleFindManyArgs): Promise<Angle[]> {
    return this.service.angles(args);
  }

  @graphql.Query(() => Angle, { nullable: true })
  async angle(
    @graphql.Args() args: AngleFindUniqueArgs
  ): Promise<Angle | null> {
    const result = await this.service.angle(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => Angle)
  async deleteAngle(
    @graphql.Args() args: DeleteAngleArgs
  ): Promise<Angle | null> {
    try {
      return await this.service.deleteAngle(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
